spring.application.name=autoloc
# JWT
jwt.secret=autoloc_secret_key_very_long_and_secure_must_be_32_chars
jwt.expiration=86400000

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MarouaneZ1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
# JPA ? crée les tables automatiquement depuis entités

# create-drop : Crée au démarrage, supprime à l'arrêt
# create : Crée au démarrage, garde à l'arrêt
# update : Met à jour le schéma si besoin, conserve les données
# validate : Vérifie que le schéma correspond, ne touche à rien
# none : Ne fait rien

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=false

# ?? Server ?????????????????????????????????????????????????
server.port=8081